### ISSUE TITLE
Default to open-source optimiser

### ISSUE THREAD

**Issue by seabbs** [ryantibs/quantgen#2]
Hi @ryantibs, 

This is a really nice package. 

We (really @sbfnk) are now using it for QRA in the UK to ensemble Covid-19 forecasts (Package: https://github.com/epiforecasts/qra). Something that initially put me off a little was the default to the closed source optimizer. Would it be possible to default instead to the open-source option or to highlight that the open-source option is available?

**Comment by ryantibs** [comment]
Glad you like it, hope you find it useful.  Sure, I changed the default to be GLPK rather than Gurobi.  However, Gurobi is free for academics (looks like your group falls in this category?) so I would strongly recommend you download and use it, because it's much faster and more stable.  I've emphasized this in the documentation.

**Comment by seabbs** [comment]
Great - thanks for changing that. 

Performance benefits duly noted!
